sudo: required
services:
    - docker

before_install:
  - docker build -t kjakobsson/docker-react -f Dockerfile.dev .

script:
  - docker run kjakobsson/docker-react npm run test -- --coverage
  
